### ISSUE TITLE
Getting error when running an example file MT2D_halfspace_AppExample.py

### ISSUE THREAD

**Issue by varsubham** [esys-escript/esys-escript.github.io#20]
When I am running an example script for inversion MT2D_halfspace_AppExample.py  I am getting the following error.

```
Traceback (most recent call last):
  File "MT2D_halfspace_AppExample.py", line 109, in <module>
    Zyx = model.getImpedance(f=frq)
  File "downunder/py_src/apps/MTModels.py", line 256, in getImpedance
  File "escriptcore/py_src/linearPDEs.py", line 1867, in getSolution
  File "escriptcore/py_src/linearPDEs.py", line 1886, in getSystem
  File "escriptcore/py_src/linearPDEs.py", line 1227, in isOperatorValid
  File "escriptcore/py_src/linearPDEs.py", line 1817, in getRequiredOperatorType
NotImplementedError: Paso requires MUMPS for complex-valued matrices.
```

I am using Debian 10 Buster

**Comment by esys-escript** [comment]
Hi varsubham,

Unfortunately the PASO library of solvers does not currently support complex valued PDEs (the MUMPS code is currently in the developmental stage). At present escript only supports complex valued PDEs if it is compiled with the Trilinos library enabled.
