### ISSUE TITLE
ValueError: isCellOriented: Finley does not know anything about function space type error

### ISSUE THREAD

**Issue by mopshell** [esys-escript/esys-escript.github.io#77]
Install file: "scripts/release_sanity.py" as "build/scripts/release_sanity.py"
/mnt/batch/tasks/shared/LS_root/mounts/clusters/carolinehu2022/code/Users/carolinehu2022/geophysics/esys-escript.github.io/bin/run-escript /mnt/batch/tasks/shared/LS_root/mounts/clusters/carolinehu2022/code/Users/carolinehu2022/geophysics/esys-escript.github.io/build/scripts/release_sanity.py
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/carolinehu2022/code/Users/carolinehu2022/geophysics/esys-escript.github.io/build/scripts/release_sanity.py", line 20, in <module>
    mypde = Poisson(domain=mydomain)
  File "escriptcore/py_src/linearPDEs.py", line 2304, in __init__
    super(Poisson, self).__init__(domain,1,1,debug)
  File "escriptcore/py_src/linearPDEs.py", line 1774, in __init__
    super(LinearPDE, self).__init__(domain,numEquations,numSolutions,isComplex,debug)
  File "escriptcore/py_src/linearPDEs.py", line 501, in __init__
    self.initializeSystem()
  File "escriptcore/py_src/linearPDEs.py", line 1274, in initializeSystem
    self.setSystemStatus()
  File "escriptcore/py_src/linearPDEs.py", line 607, in setSystemStatus
    self.__system_status=self.getDomainStatus()
  File "escriptcore/py_src/linearPDEs.py", line 593, in getDomainStatus
    return self.getDomain().getStatus()
ValueError: isCellOriented: Finley does not know anything about function space type -1435261424
scons: *** [dummy] Error 1
scons: building terminated because of errors.

**Comment by esys-escript** [comment]
Hi mopshell,

Which operating system are you currently using? Also, could you please send me the options file that you used when compiling?

- Adam

**Comment by LutzGross** [comment]
Is this still relevant?
